In [1]:
import os
import pandas as pd

path = 'data'

In [3]:
genome_scores = pd.read_csv(os.path.join(path, 'genome-scores.csv'))
genome_tags = pd.read_csv(os.path.join(path,'genome-tags.csv'))
links = pd.read_csv(os.path.join(path,'links.csv'))
movies = pd.read_csv(os.path.join(path,'movies.csv'))
ratings = pd.read_csv(os.path.join(path,'ratings.csv'))
tags = pd.read_csv(os.path.join(path,'tags.csv'))

In [4]:
genome_scores.head()

   movieId  tagId  relevance
0        1      1    0.02900
1        1      2    0.02375
2        1      3    0.05425
3        1      4    0.06875
4        1      5    0.16000

In [5]:
genome_tags.head()

   tagId           tag
0      1           007
1      2  007 (series)
2      3  18th century
3      4         1920s
4      5         1930s

In [6]:
links.head()

   movieId  imdbId   tmdbId
0        1  114709    862.0
1        2  113497   8844.0
2        3  113228  15602.0
3        4  114885  31357.0
4        5  113041  11862.0

In [7]:
movies.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [8]:
ratings.head()

   userId  movieId  rating   timestamp
0       1      307     3.5  1256677221
1       1      481     3.5  1256677456
2       1     1091     1.5  1256677471
3       1     1257     4.5  1256677460
4       1     1449     4.5  1256677264

In [9]:
tags.head()

   userId  movieId           tag   timestamp
0      14      110          epic  1443148538
1      14      110      Medieval  1443148532
2      14      260        sci-fi  1442169410
3      14      260  space action  1442169421
4      14      318  imdb top 250  1442615195

In [ ]:
ratings.query()

In [166]:
temp = genome_scores.groupby('movieId').quantile(0.9).iloc[:,1]

In [186]:
# temp

In [171]:
def addTagThreshold(x):
    if int(x['movieId']) in temp.index:
        return temp[int(x['movieId'])]
    return 2
        

data = movies.copy()
        
# newMovie = genome_scores.iloc[:,0].unique()
# newMovie = newMovie -1

In [172]:
data['tagThreshold'] = data.apply(addTagThreshold, axis=1)

In [176]:
data[data.tagThreshold != 2]

,movieId,title,genres,tagThreshold
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,0.416600
1,2,Jumanji (1995),Adventure|Children|Fantasy,0.288300
2,3,Grumpier Old Men (1995),Comedy|Romance,0.212200
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance,0.193350
4,5,Father of the Bride Part II (1995),Comedy,0.214050
5,6,Heat (1995),Action|Crime|Thriller,0.487050
6,7,Sabrina (1995),Comedy|Romance,0.231500
7,8,Tom and Huck (1995),Adventure|Children,0.170500
8,9,Sudden Death (1995),Action,0.180475
9,10,GoldenEye (1995),Action|Adventure|Thriller,0.295150
10,11,"American President, The (1995)",Comedy|Drama|Romance,0.296500
11,12,Dracula: Dead and Loving It (1995),Comedy|Horror,0.182575
12,13,Balto (1995),Adventure|Animation|Children,0.183075
13,14,Nixon (1995),Drama,0.291425
14,15,Cutthroat Island (1995),Action|Adventure|Romance,0.215075
15,16,Casino (1995),Crime|Drama,0.484875
16,17,Sense and Sensibility (1995),Drama|Romance,0.294575
17,18,Four Rooms (1995),Comedy,0.284675
18,19,Ace Ventura: When Nature Calls (1995),Comedy,0.234800
19,20,Money Train (1995),Action|Comedy|Crime|Drama|Thriller,0.205475
20,21,Get Shorty (1995),Comedy|Crime|Thriller,0.334750
21,22,Copycat (1995),Crime|Drama|Horror|Mystery|Thriller,0.260375
22,23,Assassins (1995),Action|Crime|Thriller,0.218475
23,24,Powder (1995),Drama|Sci-Fi,0.309075
24,25,Leaving Las Vegas (1995),Drama|Romance,0.408700
25,26,Othello (1995),Drama,0.264550
26,27,Now and Then (1995),Children|Drama,0.201625
27,28,Persuasion (1995),Drama|Romance,0.231550
28,29,"City of Lost Children, The (Cité des enfants p...",Adventure|Drama|Fantasy|Mystery|Sci-Fi,0.517700
29,30,Shanghai Triad (Yao a yao yao dao waipo qiao) ...,Crime|Drama,0.326075
...,...,...,...,...
53404,182913,Doctor Who: Twice Upon A Time (2017),Drama|Sci-Fi,0.592725
53450,183011,The Commuter (2018),Crime|Drama|Mystery|Thriller,0.249650
53523,183197,Dave Chappelle: Equanimity (2017),Comedy,0.455250
53536,183227,Dave Chappelle: The Bird Revelation (2017),Comedy,0.409575
53631,183421,Red Sparrow (2018),Thriller,0.338000
53712,183589,Fifty Shades Freed (2018),Drama|Romance,0.333150
53723,183611,Game Night (2018),Action|Comedy|Crime|Horror,0.256250
53726,183619,Den of Thieves (2018),Crime,0.332575
53734,183635,Maze Runner: The Death Cure (2018),Action|Mystery|Sci-Fi|Thriller,0.252575
53764,183701,12 Strong (2018),Drama|War,0.506025
53822,183833,Early Man (2018),Animation|Children|Comedy,0.364225
53849,183897,Isle of Dogs (2018),Animation|Comedy,0.503725
53855,183909,A Futile & Stupid Gesture (2018),(no genres listed),0.436325
53907,184015,When We First Met (2018),Comedy,0.249550
53908,184017,Mute (2018),Mystery|Sci-Fi|Thriller,0.348300
54007,184239,Peter Rabbit (2018),Animation,0.219225
54014,184253,The Cloverfield Paradox (2018),Horror|Mystery|Sci-Fi|Thriller,0.298200
54016,184257,Making a Murderer (2015),Crime|Documentary,0.503825
54107,184471,Tomb Raider (2018),Action|Adventure|Fantasy,0.227100
54322,184931,Death Wish (2018),Action|Crime|Drama|Thriller,0.435225
54349,184987,A Wrinkle in Time (2018),Adventure|Children|Fantasy|Sci-Fi,0.246550
54354,184997,"Love, Simon (2018)",Comedy|Drama,0.407125
54370,185029,A Quiet Place (2018),Drama|Horror|Thriller,0.452325
54418,185135,Sherlock - A Study in Pink (2010),Crime,0.711550
54558,185425,The Titan (2018),Sci-Fi,0.315600
54563,185435,"Game Over, Man! (2018)",Action|Comedy,0.270875
54623,185585,Pacific Rim: Uprising (2018),Action|Fantasy|Sci-Fi,0.234900
55091,186587,Rampage (2018),Action|Adventure|Sci-Fi,0.377700
55569,187593,Deadpool 2 (2018),Action|Comedy|Sci-Fi,0.513075
55570,187595,Solo: A Star Wars Story (2018),Action|Adventure|Children|Sci-Fi,0.393375

In [90]:
newMovie[-10:]

array([184986, 184996, 185028, 185134, 185424, 185434, 185584, 186586,
       187592, 187594])

In [102]:
movies.shape

(58098, 3)

In [81]:
data = movies.loc[newMovie,:]

In [105]:
data.index = pd.RangeIndex(1, len(data.index)+1)
data['tagThreshold'] = x
data.index = pd.RangeIndex(len(data.index))

In [106]:
data.shape

(13176, 4)

In [113]:
# data

In [110]:
actualdata = data.dropna(how='all')

In [111]:
actualdata.shape

(9174, 4)

In [112]:
actualdata

,movieId,title,genres,tagThreshold
0,1.0,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,0.416600
1,2.0,Jumanji (1995),Adventure|Children|Fantasy,0.288300
2,3.0,Grumpier Old Men (1995),Comedy|Romance,0.212200
3,4.0,Waiting to Exhale (1995),Comedy|Drama|Romance,0.193350
4,5.0,Father of the Bride Part II (1995),Comedy,0.214050
5,6.0,Heat (1995),Action|Crime|Thriller,0.487050
6,7.0,Sabrina (1995),Comedy|Romance,0.231500
7,8.0,Tom and Huck (1995),Adventure|Children,0.170500
8,9.0,Sudden Death (1995),Action,0.180475
9,10.0,GoldenEye (1995),Action|Adventure|Thriller,0.295150
10,11.0,"American President, The (1995)",Comedy|Drama|Romance,0.296500
11,12.0,Dracula: Dead and Loving It (1995),Comedy|Horror,0.182575
12,13.0,Balto (1995),Adventure|Animation|Children,0.183075
13,14.0,Nixon (1995),Drama,0.291425
14,15.0,Cutthroat Island (1995),Action|Adventure|Romance,0.215075
15,16.0,Casino (1995),Crime|Drama,0.484875
16,17.0,Sense and Sensibility (1995),Drama|Romance,0.294575
17,18.0,Four Rooms (1995),Comedy,0.284675
18,19.0,Ace Ventura: When Nature Calls (1995),Comedy,0.234800
19,20.0,Money Train (1995),Action|Comedy|Crime|Drama|Thriller,0.205475
20,21.0,Get Shorty (1995),Comedy|Crime|Thriller,0.334750
21,22.0,Copycat (1995),Crime|Drama|Horror|Mystery|Thriller,0.260375
22,23.0,Assassins (1995),Action|Crime|Thriller,0.218475
23,24.0,Powder (1995),Drama|Sci-Fi,0.309075
24,25.0,Leaving Las Vegas (1995),Drama|Romance,0.408700
25,26.0,Othello (1995),Drama,0.264550
26,27.0,Now and Then (1995),Children|Drama,0.201625
27,28.0,Persuasion (1995),Drama|Romance,0.231550
28,29.0,"City of Lost Children, The (Cité des enfants p...",Adventure|Drama|Fantasy|Mystery|Sci-Fi,0.517700
29,30.0,Shanghai Triad (Yao a yao yao dao waipo qiao) ...,Crime|Drama,0.326075
...,...,...,...,...
9144,192243.0,Contact (1992),Drama|Horror|Mystery|Thriller,NaN
9145,192333.0,Maradona (2018),Action|Comedy|Thriller,NaN
9146,192337.0,Tale of Two Sisters (1989),Drama,NaN
9147,192393.0,Night School (2018),Comedy,NaN
9148,192397.0,Rip Girls (2000),Children|Drama|Romance,NaN
9149,192407.0,Fear of Water (2015),Drama|Romance,NaN
9150,192417.0,Hubert Selby Jr: It'll Be Better Tomorrow (2006),Documentary,NaN
9151,192429.0,Nails (2017),Horror,NaN
9152,192433.0,Red Peony Gambler (1968),Action|Comedy|Drama|Romance|Thriller,NaN
9153,192441.0,Red Peony Gambler: Gambler's Obligation (1968),Drama,NaN
9154,192451.0,Dead Men (2018),Action|Drama|Western,NaN
9155,192461.0,MXP: Most Xtreme Primate (2004),Comedy,NaN
9156,192717.0,Live (2014),Comedy|Thriller,NaN
9157,192729.0,If I Leave Here Tomorrow: A Film About Lynyrd ...,Documentary,NaN
9158,192767.0,Vazante (2017),Drama,NaN
9159,192813.0,"Bert Rigby, You're a Fool (1989)",Comedy,NaN
9160,193097.0,The Life and Assassination of the Kingfish (1977),(no genres listed),NaN
9161,193163.0,What the Snow Brings (2005),(no genres listed),NaN
9162,193287.0,The World Is Yours (2018),Comedy|Crime|Drama,NaN
9163,193315.0,Five Came Back (1939),Adventure|Drama|Thriller,NaN
9164,193345.0,BBS: The Documentary (2005),Documentary,NaN
9165,193361.0,Lansky (1999),Crime|Drama,NaN
9166,193463.0,Bitter Sweet (2016),Comedy|Romance,NaN
9167,193545.0,Primas (2017),(no genres listed),NaN
9168,193549.0,Anote's Ark (2016),Documentary,NaN
9169,193599.0,Climax (2018),Drama|Horror,NaN
9170,193619.0,Buffalo Girls (1995),Western,NaN
9171,193733.0,Homecoming (2017),Children|Drama,NaN
9172,193777.0,Almost Home (2014),Adventure|Animation|Sci-Fi,NaN
9173,193843.0,Raazi (2018),Action|Drama|Thriller,NaN

In [91]:
# movies